CREATE DATABASE IF NOT EXISTS streamhub DEFAULT CHARACTER SET utf8mb4;
USE streamhub;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  login_name VARCHAR(64) NOT NULL UNIQUE,
  pwd VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS video_info (
  id VARCHAR(64) PRIMARY KEY,
  author_id INT NOT NULL,
  title VARCHAR(64) NOT NULL,
  display_ctime VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS comments (
  id VARCHAR(64) PRIMARY KEY,
  video_id VARCHAR(64) NOT NULL,
  author_id INT NOT NULL,
  content TEXT NOT NULL,
  create_time DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  session_id VARCHAR(64) PRIMARY KEY,
  TTL BIGINT NOT NULL,
  login_name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS video_del_rec (
  video_id VARCHAR(64) PRIMARY KEY
);
